x-airflow-common: &airflow-common
  extra_hosts:
    - "host.docker.internal:host-gateway"
  image: apache/airflow:2.10.3
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres/airflow
    AIRFLOW__FAB__AUTH_BACKEND: db
    AIRFLOW_ADMIN_PASS: AIRFLOW_ADMIN_PASS
    # AIRFLOW_UID: AIRFLOW_UID
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./sql:/opt/airflow/sql
    - ./logs:/opt/airflow/logs    
  user: "${AIRFLOW_UID:-50000}:0"    
  depends_on:
    - postgres

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db init &&
      airflow users create 
      --username Bazhutov 
      --firstname Aleksandr 
      --lastname '' 
      --role Admin 
      --email abazhutov@gmail.com 
      --password \"${AIRFLOW_ADMIN_PASS}\""


  airflow-webserver:
    <<: *airflow-common
    command: airflow webserver --port 8080

    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
