x-airflow-common: &airflow-common
  extra_hosts:
    - "host.docker.internal:host-gateway"
  image: apache/airflow:2.10.3
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres/airflow
    AIRFLOW_CONN_OPR_POSTGRES: "postgres://airflow:${POSTGRES_PASSWORD}@opr:5432/airflow"
    AIRFLOW_CONN_MRR_POSTGRES: "postgres://airflow:${POSTGRES_PASSWORD}@mrr:5432/airflow"
    AIRFLOW_CONN_STG_POSTGRES: "postgres://airflow:${POSTGRES_PASSWORD}@stg:5432/airflow"
    AIRFLOW_CONN_DWH_POSTGRES: "postgres://airflow:${POSTGRES_PASSWORD}@dwh:5432/airflow"    
    AIRFLOW__FAB__AUTH_BACKEND: db
    AIRFLOW_ADMIN_PASS: AIRFLOW_ADMIN_PASS
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./sql:/opt/airflow/sql
    - ./logs:/opt/airflow/logs    
  user: "${AIRFLOW_UID:-50000}:0"    
  depends_on:
    - postgres
    - opr
    - mrr
    - stg
    - dwh

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    ports:
      - "5430:5432"

  opr:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    volumes: 
      # - ./data:/var/lib/postgresql/data    
      - ./sql/opr_schema.sql:/docker-entrypoint-initdb.d/opr_schema.sql     
    ports:
      - "5431:5432"

  mrr:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    volumes: 
      # - ./data:/var/lib/postgresql/data      
      - ./sql/create_tables_mrr.sql:/docker-entrypoint-initdb.d/create_tables_mrr.sql 
    ports:
      - "5432:5432"

  stg:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    volumes:      
      # - ./data:/var/lib/postgresql/data
      - ./sql/create_tables_stg.sql:/docker-entrypoint-initdb.d/create_tables_stg.sql
    ports:
      - "5433:5432"

  dwh:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    volumes:    
      # - ./data:/var/lib/postgresql/data     
      - ./sql/create_tables_dwh.sql:/docker-entrypoint-initdb.d/create_tables_dwh.sql
    ports:
      - "5434:5432"

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db init &&
      airflow connections add 'opr_postgres' --conn-uri 'postgresql://airflow:${POSTGRES_PASSWORD}@opr:5432/airflow' &&
      airflow connections add 'mrr_postgres' --conn-uri 'postgresql://airflow:${POSTGRES_PASSWORD}@mrr:5432/airflow' &&
      airflow connections add 'stg_postgres' --conn-uri 'postgresql://airflow:${POSTGRES_PASSWORD}@stg:5432/airflow' &&
      airflow connections add 'dwh_postgres' --conn-uri 'postgresql://airflow:${POSTGRES_PASSWORD}@dwh:5432/airflow' &&
      airflow users create 
      --username admin 
      --firstname admin 
      --lastname admin 
      --role Admin 
      --email admin@admin.com 
      --password \"${AIRFLOW_ADMIN_PASS}\""


  airflow-webserver:
    <<: *airflow-common
    command: airflow webserver --port 8080

    ports:
      - "8080:8080"
      - "8793:8793"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  metabase:
    image: metabase/metabase:latest
    environment:
#      MB_DB_TYPE: "postgres"
     MB_DB_HOST: "dwh"
#      MB_DB_PORT: "5430"
#      MB_DB_USER: "airflow"
#      MB_DB_PASS: "${POSTGRES_PASSWORD}"
    #  MB_DB_DBNAME: "airflow"
    ports:
      - "3000:3000"
    volumes:
      - ./metabase_data:/metabase 
